global using DemoMS.Service.Inventory;
global using MongoDB.Bson.Serialization;
global using MongoDB.Bson.Serialization.Serializers;
global using MongoDB.Bson;
global using DemoMS.Service.Common.Configuration;
global using DemoMS.Service.Common.Repository.MongoDBDatabaseRepository.Entities.Interfaces;
global using DemoMS.Service.Common.Repository.MongoDBDatabaseRepository.Entities;
global using DemoMS.Service.Inventory.Repository.MongoDBDatabaseRepository.Entities;
global using DemoMS.Service.Inventory.DTOS;
